[phases.setup]
nixPkgs = ['nodejs_18']

[phases.build]
cmds = ['npm ci', 'npm run build']

[start]
cmd = 'node --dns-result-order=ipv4first dist/index.js'

[variables]
NODE_OPTIONS = '--dns-result-order=ipv4first --max-old-space-size=512'
NIXPACKS_NODE_VERSION = '18'